### ISSUE TITLE
Selecting a dropdown item does not save

### ISSUE THREAD

**Issue by creativeindustriesgroup** [giorgosart/react-easy-edit#148] opened 2023-01-07 13:24 UTC
**Describe the bug**
Using the following example code from the sandbox for a dropdown menu, the dropdown appears and is editable on click. Click on the select box will open the dropdowns with the items populated from generateOptionsList but clicking on an option and then clicking save does not trigger the onSave function.

Clicking to edit the field and clicking save without selecting a value does trigger the onSave function.

```
import EasyEdit, {Types} from 'react-easy-edit';

    const generateOptionsList = () => {
        return [
            { label: "First option", value: "one" },
            { label: "Second option", value: "two" },
            { label: "Third option", value: "three" }
        ];
};

    const save = (value) => {
    alert(value);
  };

return (  <td className="second-column"><EasyEdit
            type={Types.SELECT}
            options={generateOptionsList()}
            cancelOnBlur
            hideCancelButton
            onSave={() => console.log('Saved!')}
            placeholder={row.name ? row.name: "Select a Row"}
            /></td> )
```
**Expected behavior**
When choosing a dropdown option, the value is set and the console shows "Saved!" after pressing the save button.

**Screenshots**
![](https://s3.gifyu.com/images/Screen-Recording-2023-01-07-at-13.12.gif)

**Environment (please complete the following information):**
 - iOS 13.0 (22A380) running Chrome Version 108.0.5359.124.
 - React app is in a CRA Dev Server.

**Comment by giorgosart** [comment] 2023-05-01 10:12
Hi @creativeindustriesgroup I believe that this is a duplicate of #150, the problem is that you've included the `cancelOnBlur` prop and also have the Save button enabled. A temporary solution would be to remove the  `cancelOnBlur` until I come up with a fix.

**Closed by giorgosart** 2023-05-01 10:12 UTC
Labels: bug, duplicate
