### ISSUE TITLE
Attributes prop is not working

### ISSUE THREAD

**Issue by BlackboardCreative** [giorgosart/react-easy-edit#137] opened 2021-11-10 22:08 UTC
**Describe the bug**
When adding attributes `attributes={{ id: "awesome-input", class: "my-awesome-class"}}` they do not get added to the component as expected.

**To Reproduce**
1. Go to demo
2. Look at source and see demo attributes are not getting applied

**Expected behavior**
Attributes should be applied to the dom element.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by giorgosart** [comment] 2021-11-10 22:29
Hey @BlackboardCreative, thank you for logging a ticket with me!

I cannot reproduce the issue you are referring, do you mind creating a codepen with your problem?

See below expected behavour (from the demo playground):
![image](https://user-images.githubusercontent.com/1062121/141204155-32dfde03-b24e-4ac5-9deb-71a96916022f.png)

**Comment by alexDevBR** [comment] 2021-11-11 13:13
Tru using:
```viewAttributes={{ className:"my-awesome-class"}}```

**Comment by giorgosart** [comment] 2021-11-11 20:45
@alexDevBR I did and it worked. Can either of you provide a codepen replicating this issue?
![image](https://user-images.githubusercontent.com/1062121/141366321-ae67cbed-72da-478a-ba9e-8baec40654ea.png)

**Comment by alexDevBR** [comment] 2021-11-12 11:41
@giorgosart it does work. I was just pointing out to @BlackboardCreative that to change the class he should try `viewAttributtes`, instead of  `attributes`.

**Comment by giorgosart** [comment] 2021-11-12 11:44
Thank you, will be closing this down, @BlackboardCreative feel free to reopen if you are still facing any issue.

**Closed by giorgosart** 2021-11-12 11:44 UTC
