### ISSUE TITLE
Toggle edit mode with `editMode` prop

### ISSUE THREAD

**Issue by orbitfum** [giorgosart/react-easy-edit#122] opened 2020-12-23 17:15 UTC
**Describe the bug**
Toggle edit mode with `editMode` prop not working after first save with  `editMode`

**To Reproduce**
1. Go to 'https://codesandbox.io/s/toggle-edit-mode-forked-4cg7e?file=/src/index.js'
2. Click on 'edit' button to toggle on
3. Edit any field
4. Click on 'save' button
5. Click on 'edit' button to toggle off
6. Click again on 'edit' button to toggle on
7. Bug -> Can't update field

**Expected behavior**
After step 6, able to edit again.

**Comment by giorgosart** [comment] 2020-12-26 17:21
Thank you for logging this @orbitfum, will take a look as soon as i can.

**Comment by giorgosart** [comment] 2021-01-17 23:41
Hey @orbitfum the issue is now addressed in [react-easy-edit@1.13.1](https://www.npmjs.com/package/react-easy-edit), please update your project and let me know if you face any issues.

**Closed by giorgosart** 2021-01-17 23:41 UTC
Labels: bug, help wanted
